FROM rust:1.79

# Set the working directory inside the container
WORKDIR /app

# Clone the repository and build the project
RUN git clone --branch debug --single-branch https://github.com/quertc/signer-proxy.git && \
    cd signer-proxy && \
    cargo build --release && \
    mv ./target/release/signer-proxy /app/

CMD ["/app/signer-proxy", "yubihsm", "-d", "0018951531", "-a", "4", "-p", "123", "serve"]
