FROM node:20

RUN apt-get update && apt-get install -y jq

WORKDIR /app

COPY /data/deployments/artifact.json ./data/deployments/artifact.json
COPY ui.env ./.env
COPY /scripts/config-bridge-ui.sh .
RUN chmod +x config-bridge-ui.sh && ./config-bridge-ui.sh

COPY ./bridge/ui/package*.json ./

RUN npm install

COPY ./bridge/ui .

RUN npm run build

FROM nginx:alpine AS production

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
