#!/bin/bash

# Define colors
ORANGE='\e[0;33m'
BLUE='\e[0;34m'
RED='\e[0;31m'
GREEN='\e[0;32m'
NC='\e[0m'

# Check if .env file exists
if [ ! -f .env ]; then
  if [ -f .env.example ]; then
    echo -e "${RED}Error${NC}: .env file not found."
    echo -ne "${ORANGE}Do you want to use .env.example and rename it to .env? (yes/no): ${NC}"
    read -r rename_confirm
    if [[ "$rename_confirm" =~ ^(yes|y)$ ]]; then
      mv .env.example .env
      echo -e "${GREEN}.env.example has been renamed to .env.${NC}"
    else
      echo "Exiting."
      exit 1
    fi
  else
    echo -e "${RED}Error${NC}: .env and .env.example files not found. Exiting."
    exit 1
  fi
fi

# Load environment variables from .env file
# shellcheck disable=SC1091
source .env

# Initialize the command
command="docker compose"

# Add profiles based on SEQUENCER_MODE, SIGNER_PROXY and Celestia support
[ "$SEQUENCER_MODE" = "true" ] && command+=" --profile sequencer"
[ "$CELESTIA_MODE" = "true" ] && command+=" --profile celestia"

if [ "$SEQUENCER_MODE" = "true" ] && [ "$SIGNER_PROXY" = "true" ]; then
  command+=" --profile signer-proxy"
fi

if [ "$SKIP_DEPLOYMENT_CHECK" = "true" ]; then
  echo -e "${ORANGE}NOTE${NC}: Only genesis.json and rollup.json will be checked (SKIP_DEPLOYMENT_CHECK=$SKIP_DEPLOYMENT_CHECK)."
fi

if [ "$SKIP_HEALTHCHECK" = "true" ]; then
  echo -e "${ORANGE}WARNING${NC}: Celestia da light node sync check will be skipped (SKIP_HEALTHCHECK=$SKIP_HEALTHCHECK)."
fi

# Add the rest of the command
command+=" up --build -d"

# Confirm before running the command
echo -ne "About to run: ${BLUE}$command${NC} (SEQUENCER_MODE: $SEQUENCER_MODE, CELESTIA_MODE: $CELESTIA_MODE, SIGNER_PROXY: $SIGNER_PROXY). Do you want to continue? (yes/no): "
read -r confirm
if [[ "$confirm" =~ ^(yes|y)$ ]]; then
  eval "$command"
else
  echo "Command execution cancelled."
fi
