#!/bin/bash

# Load environment variables from .env file
source .env

# Initialize the command
command="docker compose"

# Add profiles based on SEQUENCER_MODE and Celestia support
[ "$SEQUENCER_MODE" = "true" ] && command+=" --profile sequencer"
[ "$CELESTIA_MODE" = "true" ] && command+=" --profile celestia"

if [ "$SKIP_HEALTHCHECK" = "true" ]; then
  echo "Celestia da light node sync check will be skipped (SKIP_HEALTHCHECK=$SKIP_HEALTHCHECK)..."
fi

# Add the rest of the command
command+=" up --build -d"

# Confirm before running the command
read -p "About to run: $command (SEQUENCER_MODE: $SEQUENCER_MODE, CELESTIA_MODE: $CELESTIA_MODE). Do you want to continue? (yes/no): " confirm
if [[ "$confirm" =~ ^(yes|y)$ ]]; then
  eval $command
else
  echo "Command execution cancelled."
fi
